# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall

EXTRA_CFLAGS += -Itechpack/audio/include
EXTRA_CFLAGS += -Itechpack/audio/include/uapi

EXTRA_CFLAGS += -DCONFIG_SND_SOC_AOV_TRIGGER

ifeq ($(CONFIG_CHANNEL_DTB), y)
EXTRA_CFLAGS += -DCONFIG_TAS2560_REGMAP -DCONFIG_TAS2560_CODEC -DCONFIG_TAS2560_MISC -DCONFIG_SND_SOC_TAS2560
endif

ifeq ($(KDIR),)
PLMA_HOSTSW_DIR=$(realpath -f $(srctree)/$(src))
else
PLMA_HOSTSW_DIR=$(realpath -f $(src))
endif
GIT_VERSION=$(shell cd $(PLMA_HOSTSW_DIR); git describe --tags --dirty --match "v[0-9]*.[0-9]*.[0-9]*")
EXTRA_CFLAGS += -DTFA98XX_GIT_VERSIONS=\"$(GIT_VERSION)\"
# debugging support (also enables trace_printk)
EXTRA_CFLAGS += -DTFA9874_NONDSP_STEREO
EXTRA_CFLAGS += -Isound/soc/codecs/inc
EXTRA_CFLAGS += -Werror

ifeq ($(CONFIG_RIVER_DTB), y)
cirrus_madera-objs = madera.o madera-slimbus.o
obj-y += cirrus_madera.o

cirrus_wm_adsp-objs = wm_adsp.o
obj-y += cirrus_wm_adsp.o

cirrus_cs35l35-objs = cs35l35.o
obj-y += cirrus_cs35l35.o

cirrus_cs35l36-objs = cs35l36.o cs35l36-tables.o
obj-y += cirrus_cs35l36.o

cirrus_cs47l35-objs =  cs47l35.o
obj-y += cirrus_cs47l35.o

cirrus_cs47l90-objs =  cs47l90.o
obj-y += cirrus_cs47l90.o

obj-y += aov_trigger.o

cirrus_cs35l41-objs = cs35l41.o cs35l41-tables.o
obj-y += cirrus_cs35l41.o

ifneq ($(filter m y,$(CONFIG_SND_SOC_CS35L41_SPI)),)
   cirrus_cs35l41-objs += cs35l41-spi.o
else
   cirrus_cs35l41-objs += cs35l41-i2c.o
endif

cirrus_playback-objs = msm-cirrus-playback.o
obj-y += cirrus_playback.o
endif

ifeq ($(CONFIG_OCEAN_DTB), y)
snd_soc_tfa9874-objs += tfa98xx.o
snd_soc_tfa9874-objs += tfa_container.o
snd_soc_tfa9874-objs += tfa_dsp.o
snd_soc_tfa9874-objs += tfa_init.o
ifdef TFA_DEBUG
EXTRA_CFLAGS += -DTFA_DEBUG -DDEBUG
snd_soc_tfa9874-objs += tfa_debug.o
endif
obj-y += snd_soc_tfa9874.o
endif

ifeq ($(CONFIG_CHANNEL_DTB), y)
tas2560-objs = tas2560-core.o tas2560-misc.o tas2560-codec.o tas2560-regmap.o
obj-y += tas2560.o

tas2560_algo-objs = tas2560-algo.o
obj-y += tas2560_algo.o

tas2560_calib-objs = tas2560-calib.o
obj-y += tas2560_calib.o
endif
