# Makefile for the Himax MMI touchscreen drivers.

obj-$(CONFIG_TOUCHSCREEN_HIMAX_MMI_I2C) += himax_mmi.o
himax_mmi-objs += himax_ic_HX83112.o
himax_mmi-objs += himax_ic_HX83102.o
himax_mmi-objs += himax_platform.o
himax_mmi-objs += himax_inspection.o
himax_mmi-objs += himax_ic_incell_core.o
himax_mmi-objs += himax_common.o
himax_mmi-objs += himax_debug.o
