#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_MMI) += focaltech_mmi.o
focaltech_mmi-objs += focaltech_ts.o
focaltech_mmi-objs += focaltech_flash.o
focaltech_mmi-objs += focaltech_upgrade_ft8716.o
focaltech_mmi-objs += focaltech_upgrade_idc.o
focaltech_mmi-objs += focaltech_upgrade_ft5x46.o
focaltech_mmi-objs += focaltech_upgrade_ft5422u.o
focaltech_mmi-objs += focaltech_upgrade_ft8006u.o
