#
# Makefile for the Novatek NT36525 touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_NT36525) += nova_36525_mmi.o 
nova_36525_mmi-objs += nt36xxx.o
nova_36525_mmi-objs += nt36xxx_ext_proc.o
nova_36525_mmi-objs += nt36xxx_fw_update.o
nova_36525_mmi-objs += nt36xxx_mp_ctrlram.o
