#
# Makefile for the Novatek NT36xxx touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_NT36xxx) += nova_mmi.o 
nova_mmi-objs += nt36xxx.o
nova_mmi-objs += nt36xxx_ext_proc.o
nova_mmi-objs += nt36xxx_fw_update.o
nova_mmi-objs += nt36xxx_mp_ctrlram.o
